server:
  port: 9089

spring:
  application:
    name: system-service
  data:
    neo4j:
      uri: bolt://10.10.71.2:7687
      username: neo4j
      password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
