server:
  port: 8082

spring:
  application:
    name: system-service
  datasource:
    url: jdbc:mariadb://42.194.173.207:31234/dispatch_business?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: root
    password: wjb2022
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
  redis:
    host: 10.10.90.127
    port: 6379
    password: 123456
    jedis:
      pool:
        # 最小空闲连接数
        min-idle: 0
        # 最大空闲连接数
        max-idle: 8
        # 最大活跃连接数，负数为不限制
        max-active: 8
        # 等待可用连接的最大时间，负数为不限制
        max-wait: 1ms
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}